//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS_PACIFIC.Consumos {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Servicios", Namespace="Testing")]
    public enum Servicios : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Todos = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TAE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pago_de_Servicio = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tarjeta_Bancaria = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Factura_Electronica = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fidelizacion = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transfer = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Opcion", Namespace="Testing")]
    public enum Opcion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Year = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trimestre = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mes_Y_Year = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Carriers", Namespace="Testing")]
    public enum Carriers : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Todos = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOVISTAR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IUSACELL = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TELCEL = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNEFON = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NEXTEL = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="listas", Namespace="Testing")]
    public enum listas : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        grupos = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        regiones = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        perfiles = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        usuarios = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        servicios = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        monedas = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        productos = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        reglas = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Consumos.IPSServicios")]
    public interface IPSServicios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/ValidaUsuario", ReplyAction="http://tempuri.org/IPSServicios/ValidaUsuarioResponse")]
        string ValidaUsuario(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/ValidaUsuarioAdministracion", ReplyAction="http://tempuri.org/IPSServicios/ValidaUsuarioAdministracionResponse")]
        string ValidaUsuarioAdministracion(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/BuscaCliente", ReplyAction="http://tempuri.org/IPSServicios/BuscaClienteResponse")]
        string BuscaCliente(string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/BuscaClienteRazon", ReplyAction="http://tempuri.org/IPSServicios/BuscaClienteRazonResponse")]
        string BuscaClienteRazon(string razonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/GuardaClientes", ReplyAction="http://tempuri.org/IPSServicios/GuardaClientesResponse")]
        string GuardaClientes(
                    string usuario, 
                    string clave, 
                    string RFC, 
                    string Nombre, 
                    string RazonSocial, 
                    string Calle, 
                    string NumExterior, 
                    string NumInterior, 
                    string CodigoPostal, 
                    string TipoAsentamiento, 
                    string Asentamiento, 
                    string Ciudad, 
                    string Municipio, 
                    string Estado, 
                    string Pais, 
                    string CorreoFacturas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/Login", ReplyAction="http://tempuri.org/IPSServicios/LoginResponse")]
        string Login(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/LoginPortal", ReplyAction="http://tempuri.org/IPSServicios/LoginPortalResponse")]
        string LoginPortal(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/GuardaUsuario", ReplyAction="http://tempuri.org/IPSServicios/GuardaUsuarioResponse")]
        string GuardaUsuario(string xmlUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/GuardaPermisosUsuario", ReplyAction="http://tempuri.org/IPSServicios/GuardaPermisosUsuarioResponse")]
        string GuardaPermisosUsuario(string xmlUsuario, string Codigo_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaUsuario", ReplyAction="http://tempuri.org/IPSServicios/DespliegaUsuarioResponse")]
        string DespliegaUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaPermisosUsuario", ReplyAction="http://tempuri.org/IPSServicios/DespliegaPermisosUsuarioResponse")]
        string DespliegaPermisosUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/EliminaUsuario", ReplyAction="http://tempuri.org/IPSServicios/EliminaUsuarioResponse")]
        string EliminaUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/ListaUsuario", ReplyAction="http://tempuri.org/IPSServicios/ListaUsuarioResponse")]
        string ListaUsuario(string idGrupo, string idRegion, string estatus, string posicion, string numRegistros, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/ListaUsuarioPadre", ReplyAction="http://tempuri.org/IPSServicios/ListaUsuarioPadreResponse")]
        string ListaUsuarioPadre(string idUsuario, string Codigo_Grupo, string idBusqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/ListaUsuarioHijos", ReplyAction="http://tempuri.org/IPSServicios/ListaUsuarioHijosResponse")]
        string ListaUsuarioHijos(string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/pathHijo", ReplyAction="http://tempuri.org/IPSServicios/pathHijoResponse")]
        string pathHijo(string idHijo, string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/EliminaRegion", ReplyAction="http://tempuri.org/IPSServicios/EliminaRegionResponse")]
        string EliminaRegion(string idRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/GuardaRegion", ReplyAction="http://tempuri.org/IPSServicios/GuardaRegionResponse")]
        string GuardaRegion(string idRegion, string descripcionRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/EliminaGrupo", ReplyAction="http://tempuri.org/IPSServicios/EliminaGrupoResponse")]
        string EliminaGrupo(string idGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/GuardaGrupo", ReplyAction="http://tempuri.org/IPSServicios/GuardaGrupoResponse")]
        string GuardaGrupo(string idGrupo, string descripcionGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/EliminaProveedor", ReplyAction="http://tempuri.org/IPSServicios/EliminaProveedorResponse")]
        string EliminaProveedor(string idProveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/GuardaProveedor", ReplyAction="http://tempuri.org/IPSServicios/GuardaProveedorResponse")]
        string GuardaProveedor(string idProvvedor, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaDatosProveedor", ReplyAction="http://tempuri.org/IPSServicios/DespliegaDatosProveedorResponse")]
        string DespliegaDatosProveedor(string idProveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/GuardaServicio", ReplyAction="http://tempuri.org/IPSServicios/GuardaServicioResponse")]
        string GuardaServicio(string xmlUsuario, PS_PACIFIC.Consumos.Servicios Servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaServicioUsuario", ReplyAction="http://tempuri.org/IPSServicios/DespliegaServicioUsuarioResponse")]
        string DespliegaServicioUsuario(string idusuario, PS_PACIFIC.Consumos.Servicios Servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/EliminaSucuarsal", ReplyAction="http://tempuri.org/IPSServicios/EliminaSucuarsalResponse")]
        string EliminaSucuarsal(string Id_Sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/EliminaTerminal", ReplyAction="http://tempuri.org/IPSServicios/EliminaTerminalResponse")]
        string EliminaTerminal(string Id_Terminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/GuardaTerminal", ReplyAction="http://tempuri.org/IPSServicios/GuardaTerminalResponse")]
        string GuardaTerminal(string xmlTerminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/GuardaSucursal", ReplyAction="http://tempuri.org/IPSServicios/GuardaSucursalResponse")]
        string GuardaSucursal(string xmlSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaPeriodo", ReplyAction="http://tempuri.org/IPSServicios/DespliegaPeriodoResponse")]
        string DespliegaPeriodo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaAplicaciones", ReplyAction="http://tempuri.org/IPSServicios/DespliegaAplicacionesResponse")]
        string DespliegaAplicaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaTiposConsumo", ReplyAction="http://tempuri.org/IPSServicios/DespliegaTiposConsumoResponse")]
        string DespliegaTiposConsumo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/GuardaProducto", ReplyAction="http://tempuri.org/IPSServicios/GuardaProductoResponse")]
        string GuardaProducto(string xmlUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/EliminaProducto", ReplyAction="http://tempuri.org/IPSServicios/EliminaProductoResponse")]
        string EliminaProducto(string idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaProducto", ReplyAction="http://tempuri.org/IPSServicios/DespliegaProductoResponse")]
        string DespliegaProducto(string idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/GuardaProductoUsuario", ReplyAction="http://tempuri.org/IPSServicios/GuardaProductoUsuarioResponse")]
        string GuardaProductoUsuario(string xmlProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaProductosUsuario", ReplyAction="http://tempuri.org/IPSServicios/DespliegaProductosUsuarioResponse")]
        string DespliegaProductosUsuario(string Id_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/BorrarProductoUsuario", ReplyAction="http://tempuri.org/IPSServicios/BorrarProductoUsuarioResponse")]
        string BorrarProductoUsuario(string Id_Usuario, string Id_Producto, string Id_Aplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/ApruebaPaquetesTransaccion", ReplyAction="http://tempuri.org/IPSServicios/ApruebaPaquetesTransaccionResponse")]
        string ApruebaPaquetesTransaccion(int idAplicacion, string codigoUsuario, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/SaldoToken", ReplyAction="http://tempuri.org/IPSServicios/SaldoTokenResponse")]
        string SaldoToken(int idAplicacion, string codigoUsuario, int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/TransaccionAC", ReplyAction="http://tempuri.org/IPSServicios/TransaccionACResponse")]
        string TransaccionAC(int idAplicacion, string codigoUsuario, int cantidad, string archivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/GuardaTablaComerciales", ReplyAction="http://tempuri.org/IPSServicios/GuardaTablaComercialesResponse")]
        string GuardaTablaComerciales(string xmlUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/EliminaComerciales", ReplyAction="http://tempuri.org/IPSServicios/EliminaComercialesResponse")]
        string EliminaComerciales(string Id_Tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaComerciales", ReplyAction="http://tempuri.org/IPSServicios/DespliegaComercialesResponse")]
        string DespliegaComerciales(string Id_Tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/CargaTokens", ReplyAction="http://tempuri.org/IPSServicios/CargaTokensResponse")]
        string CargaTokens(string xmlUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/TrasferenciaTokens", ReplyAction="http://tempuri.org/IPSServicios/TrasferenciaTokensResponse")]
        string TrasferenciaTokens(string xmlUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaDestinos", ReplyAction="http://tempuri.org/IPSServicios/DespliegaDestinosResponse")]
        string DespliegaDestinos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/GuardaAviso", ReplyAction="http://tempuri.org/IPSServicios/GuardaAvisoResponse")]
        string GuardaAviso(string xmlUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/EliminaAviso", ReplyAction="http://tempuri.org/IPSServicios/EliminaAvisoResponse")]
        string EliminaAviso(string IdAviso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaAviso", ReplyAction="http://tempuri.org/IPSServicios/DespliegaAvisoResponse")]
        string DespliegaAviso();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/RecargasHistoricosGrafica", ReplyAction="http://tempuri.org/IPSServicios/RecargasHistoricosGraficaResponse")]
        string RecargasHistoricosGrafica(string Mes, string Year, PS_PACIFIC.Consumos.Opcion Opciones, string IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/RecargaHistoricoGrid", ReplyAction="http://tempuri.org/IPSServicios/RecargaHistoricoGridResponse")]
        string RecargaHistoricoGrid(string Del, string Al, PS_PACIFIC.Consumos.Carriers Carrier, string posicion, string numRegistros, string IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/AgregarComercio", ReplyAction="http://tempuri.org/IPSServicios/AgregarComercioResponse")]
        string AgregarComercio(string xmlUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/ElimanaComercio", ReplyAction="http://tempuri.org/IPSServicios/ElimanaComercioResponse")]
        string ElimanaComercio(string Token, string Id_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/HistoricosPDSGrafica", ReplyAction="http://tempuri.org/IPSServicios/HistoricosPDSGraficaResponse")]
        string HistoricosPDSGrafica(string Mes, string Year, PS_PACIFIC.Consumos.Opcion Opciones, string IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/HistoricoPDSGrid", ReplyAction="http://tempuri.org/IPSServicios/HistoricoPDSGridResponse")]
        string HistoricoPDSGrid(string Del, string Al, string Carrier, string posicion, string numRegistros, string IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/HistoricosTCGrafica", ReplyAction="http://tempuri.org/IPSServicios/HistoricosTCGraficaResponse")]
        string HistoricosTCGrafica(string Mes, string Year, PS_PACIFIC.Consumos.Opcion Opciones, string IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/HistoricoTCGrid", ReplyAction="http://tempuri.org/IPSServicios/HistoricoTCGridResponse")]
        string HistoricoTCGrid(string Del, string Al, string posicion, string numRegistros, string IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/HistoricosTranferGrafica", ReplyAction="http://tempuri.org/IPSServicios/HistoricosTranferGraficaResponse")]
        string HistoricosTranferGrafica(string Mes, string Year, PS_PACIFIC.Consumos.Opcion Opciones, string IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/HistoricoTranferGrid", ReplyAction="http://tempuri.org/IPSServicios/HistoricoTranferGridResponse")]
        string HistoricoTranferGrid(string Del, string Al, string posicion, string numRegistros, string IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/HistoricoSFEGrafica", ReplyAction="http://tempuri.org/IPSServicios/HistoricoSFEGraficaResponse")]
        string HistoricoSFEGrafica(string Mes, string Year, PS_PACIFIC.Consumos.Opcion Opciones, string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/HistoricoSFEGrid", ReplyAction="http://tempuri.org/IPSServicios/HistoricoSFEGridResponse")]
        string HistoricoSFEGrid(string idUsuario, string del, string al, string posicion, string numRegistros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/ObtenerPDF", ReplyAction="http://tempuri.org/IPSServicios/ObtenerPDFResponse")]
        byte[] ObtenerPDF(string idUsuario, string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/ObtenerCFDi", ReplyAction="http://tempuri.org/IPSServicios/ObtenerCFDiResponse")]
        string ObtenerCFDi(string idUsuario, string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/ActualizarEstatusCFDi", ReplyAction="http://tempuri.org/IPSServicios/ActualizarEstatusCFDiResponse")]
        string ActualizarEstatusCFDi(string idUsuario, string UUID, bool Estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaClientesFE", ReplyAction="http://tempuri.org/IPSServicios/DespliegaClientesFEResponse")]
        string DespliegaClientesFE(string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/CargarFolios", ReplyAction="http://tempuri.org/IPSServicios/CargarFoliosResponse")]
        string CargarFolios(string idUsuario, string idDestinoUsuario, int Cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/FoliosRestantes", ReplyAction="http://tempuri.org/IPSServicios/FoliosRestantesResponse")]
        string FoliosRestantes(string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/TranferirFolios", ReplyAction="http://tempuri.org/IPSServicios/TranferirFoliosResponse")]
        string TranferirFolios(string idUsuario, string idOrigenUsuario, string rfcDestino, int Cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/RazonSocial", ReplyAction="http://tempuri.org/IPSServicios/RazonSocialResponse")]
        string RazonSocial(string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/ConsultarComprasEmisores", ReplyAction="http://tempuri.org/IPSServicios/ConsultarComprasEmisoresResponse")]
        string ConsultarComprasEmisores(string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/ValidacionPassword", ReplyAction="http://tempuri.org/IPSServicios/ValidacionPasswordResponse")]
        bool ValidacionPassword(string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaFormatos", ReplyAction="http://tempuri.org/IPSServicios/DespliegaFormatosResponse")]
        string DespliegaFormatos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaEstatus", ReplyAction="http://tempuri.org/IPSServicios/DespliegaEstatusResponse")]
        string DespliegaEstatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaLista", ReplyAction="http://tempuri.org/IPSServicios/DespliegaListaResponse")]
        string DespliegaLista(PS_PACIFIC.Consumos.listas lista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/DespliegaProveedor", ReplyAction="http://tempuri.org/IPSServicios/DespliegaProveedorResponse")]
        string DespliegaProveedor(PS_PACIFIC.Consumos.Servicios Servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/BuscaTipoAsentamiento", ReplyAction="http://tempuri.org/IPSServicios/BuscaTipoAsentamientoResponse")]
        string BuscaTipoAsentamiento(string pais, string cp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/BuscaAsentamiento", ReplyAction="http://tempuri.org/IPSServicios/BuscaAsentamientoResponse")]
        string BuscaAsentamiento(string pais, string cp, string tipoAsentamiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/Paises", ReplyAction="http://tempuri.org/IPSServicios/PaisesResponse")]
        string Paises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/BuscaEstados", ReplyAction="http://tempuri.org/IPSServicios/BuscaEstadosResponse")]
        string BuscaEstados(string pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/BuscaMunicipio", ReplyAction="http://tempuri.org/IPSServicios/BuscaMunicipioResponse")]
        string BuscaMunicipio(string pais, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/BuscaCiudad", ReplyAction="http://tempuri.org/IPSServicios/BuscaCiudadResponse")]
        string BuscaCiudad(string pais, string estado, string municipio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/BuscaCP", ReplyAction="http://tempuri.org/IPSServicios/BuscaCPResponse")]
        string BuscaCP(string pais, string estado, string municipio, string ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPSServicios/finc", ReplyAction="http://tempuri.org/IPSServicios/fincResponse")]
        string finc();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPSServiciosChannel : PS_PACIFIC.Consumos.IPSServicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PSServiciosClient : System.ServiceModel.ClientBase<PS_PACIFIC.Consumos.IPSServicios>, PS_PACIFIC.Consumos.IPSServicios {
        
        public PSServiciosClient() {
        }
        
        public PSServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PSServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PSServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PSServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ValidaUsuario(string usuario, string clave) {
            return base.Channel.ValidaUsuario(usuario, clave);
        }
        
        public string ValidaUsuarioAdministracion(string usuario, string clave) {
            return base.Channel.ValidaUsuarioAdministracion(usuario, clave);
        }
        
        public string BuscaCliente(string rfc) {
            return base.Channel.BuscaCliente(rfc);
        }
        
        public string BuscaClienteRazon(string razonSocial) {
            return base.Channel.BuscaClienteRazon(razonSocial);
        }
        
        public string GuardaClientes(
                    string usuario, 
                    string clave, 
                    string RFC, 
                    string Nombre, 
                    string RazonSocial, 
                    string Calle, 
                    string NumExterior, 
                    string NumInterior, 
                    string CodigoPostal, 
                    string TipoAsentamiento, 
                    string Asentamiento, 
                    string Ciudad, 
                    string Municipio, 
                    string Estado, 
                    string Pais, 
                    string CorreoFacturas) {
            return base.Channel.GuardaClientes(usuario, clave, RFC, Nombre, RazonSocial, Calle, NumExterior, NumInterior, CodigoPostal, TipoAsentamiento, Asentamiento, Ciudad, Municipio, Estado, Pais, CorreoFacturas);
        }
        
        public string Login(string usuario, string clave) {
            return base.Channel.Login(usuario, clave);
        }
        
        public string LoginPortal(string usuario, string clave) {
            return base.Channel.LoginPortal(usuario, clave);
        }
        
        public string GuardaUsuario(string xmlUsuario) {
            return base.Channel.GuardaUsuario(xmlUsuario);
        }
        
        public string GuardaPermisosUsuario(string xmlUsuario, string Codigo_Usuario) {
            return base.Channel.GuardaPermisosUsuario(xmlUsuario, Codigo_Usuario);
        }
        
        public string DespliegaUsuario(string usuario) {
            return base.Channel.DespliegaUsuario(usuario);
        }
        
        public string DespliegaPermisosUsuario(string usuario) {
            return base.Channel.DespliegaPermisosUsuario(usuario);
        }
        
        public string EliminaUsuario(string usuario) {
            return base.Channel.EliminaUsuario(usuario);
        }
        
        public string ListaUsuario(string idGrupo, string idRegion, string estatus, string posicion, string numRegistros, string nombre) {
            return base.Channel.ListaUsuario(idGrupo, idRegion, estatus, posicion, numRegistros, nombre);
        }
        
        public string ListaUsuarioPadre(string idUsuario, string Codigo_Grupo, string idBusqueda) {
            return base.Channel.ListaUsuarioPadre(idUsuario, Codigo_Grupo, idBusqueda);
        }
        
        public string ListaUsuarioHijos(string idUsuario) {
            return base.Channel.ListaUsuarioHijos(idUsuario);
        }
        
        public string pathHijo(string idHijo, string idUsuario) {
            return base.Channel.pathHijo(idHijo, idUsuario);
        }
        
        public string EliminaRegion(string idRegion) {
            return base.Channel.EliminaRegion(idRegion);
        }
        
        public string GuardaRegion(string idRegion, string descripcionRegion) {
            return base.Channel.GuardaRegion(idRegion, descripcionRegion);
        }
        
        public string EliminaGrupo(string idGrupo) {
            return base.Channel.EliminaGrupo(idGrupo);
        }
        
        public string GuardaGrupo(string idGrupo, string descripcionGrupo) {
            return base.Channel.GuardaGrupo(idGrupo, descripcionGrupo);
        }
        
        public string EliminaProveedor(string idProveedor) {
            return base.Channel.EliminaProveedor(idProveedor);
        }
        
        public string GuardaProveedor(string idProvvedor, string xml) {
            return base.Channel.GuardaProveedor(idProvvedor, xml);
        }
        
        public string DespliegaDatosProveedor(string idProveedor) {
            return base.Channel.DespliegaDatosProveedor(idProveedor);
        }
        
        public string GuardaServicio(string xmlUsuario, PS_PACIFIC.Consumos.Servicios Servicio) {
            return base.Channel.GuardaServicio(xmlUsuario, Servicio);
        }
        
        public string DespliegaServicioUsuario(string idusuario, PS_PACIFIC.Consumos.Servicios Servicio) {
            return base.Channel.DespliegaServicioUsuario(idusuario, Servicio);
        }
        
        public string EliminaSucuarsal(string Id_Sucursal) {
            return base.Channel.EliminaSucuarsal(Id_Sucursal);
        }
        
        public string EliminaTerminal(string Id_Terminal) {
            return base.Channel.EliminaTerminal(Id_Terminal);
        }
        
        public string GuardaTerminal(string xmlTerminal) {
            return base.Channel.GuardaTerminal(xmlTerminal);
        }
        
        public string GuardaSucursal(string xmlSucursal) {
            return base.Channel.GuardaSucursal(xmlSucursal);
        }
        
        public string DespliegaPeriodo() {
            return base.Channel.DespliegaPeriodo();
        }
        
        public string DespliegaAplicaciones() {
            return base.Channel.DespliegaAplicaciones();
        }
        
        public string DespliegaTiposConsumo() {
            return base.Channel.DespliegaTiposConsumo();
        }
        
        public string GuardaProducto(string xmlUsuario) {
            return base.Channel.GuardaProducto(xmlUsuario);
        }
        
        public string EliminaProducto(string idProducto) {
            return base.Channel.EliminaProducto(idProducto);
        }
        
        public string DespliegaProducto(string idProducto) {
            return base.Channel.DespliegaProducto(idProducto);
        }
        
        public string GuardaProductoUsuario(string xmlProducto) {
            return base.Channel.GuardaProductoUsuario(xmlProducto);
        }
        
        public string DespliegaProductosUsuario(string Id_Usuario) {
            return base.Channel.DespliegaProductosUsuario(Id_Usuario);
        }
        
        public string BorrarProductoUsuario(string Id_Usuario, string Id_Producto, string Id_Aplicacion) {
            return base.Channel.BorrarProductoUsuario(Id_Usuario, Id_Producto, Id_Aplicacion);
        }
        
        public string ApruebaPaquetesTransaccion(int idAplicacion, string codigoUsuario, int cantidad) {
            return base.Channel.ApruebaPaquetesTransaccion(idAplicacion, codigoUsuario, cantidad);
        }
        
        public string SaldoToken(int idAplicacion, string codigoUsuario, int idProducto) {
            return base.Channel.SaldoToken(idAplicacion, codigoUsuario, idProducto);
        }
        
        public string TransaccionAC(int idAplicacion, string codigoUsuario, int cantidad, string archivo) {
            return base.Channel.TransaccionAC(idAplicacion, codigoUsuario, cantidad, archivo);
        }
        
        public string GuardaTablaComerciales(string xmlUsuario) {
            return base.Channel.GuardaTablaComerciales(xmlUsuario);
        }
        
        public string EliminaComerciales(string Id_Tabla) {
            return base.Channel.EliminaComerciales(Id_Tabla);
        }
        
        public string DespliegaComerciales(string Id_Tabla) {
            return base.Channel.DespliegaComerciales(Id_Tabla);
        }
        
        public string CargaTokens(string xmlUsuario) {
            return base.Channel.CargaTokens(xmlUsuario);
        }
        
        public string TrasferenciaTokens(string xmlUsuario) {
            return base.Channel.TrasferenciaTokens(xmlUsuario);
        }
        
        public string DespliegaDestinos() {
            return base.Channel.DespliegaDestinos();
        }
        
        public string GuardaAviso(string xmlUsuario) {
            return base.Channel.GuardaAviso(xmlUsuario);
        }
        
        public string EliminaAviso(string IdAviso) {
            return base.Channel.EliminaAviso(IdAviso);
        }
        
        public string DespliegaAviso() {
            return base.Channel.DespliegaAviso();
        }
        
        public string RecargasHistoricosGrafica(string Mes, string Year, PS_PACIFIC.Consumos.Opcion Opciones, string IdCliente) {
            return base.Channel.RecargasHistoricosGrafica(Mes, Year, Opciones, IdCliente);
        }
        
        public string RecargaHistoricoGrid(string Del, string Al, PS_PACIFIC.Consumos.Carriers Carrier, string posicion, string numRegistros, string IdCliente) {
            return base.Channel.RecargaHistoricoGrid(Del, Al, Carrier, posicion, numRegistros, IdCliente);
        }
        
        public string AgregarComercio(string xmlUsuario) {
            return base.Channel.AgregarComercio(xmlUsuario);
        }
        
        public string ElimanaComercio(string Token, string Id_Usuario) {
            return base.Channel.ElimanaComercio(Token, Id_Usuario);
        }
        
        public string HistoricosPDSGrafica(string Mes, string Year, PS_PACIFIC.Consumos.Opcion Opciones, string IdCliente) {
            return base.Channel.HistoricosPDSGrafica(Mes, Year, Opciones, IdCliente);
        }
        
        public string HistoricoPDSGrid(string Del, string Al, string Carrier, string posicion, string numRegistros, string IdCliente) {
            return base.Channel.HistoricoPDSGrid(Del, Al, Carrier, posicion, numRegistros, IdCliente);
        }
        
        public string HistoricosTCGrafica(string Mes, string Year, PS_PACIFIC.Consumos.Opcion Opciones, string IdCliente) {
            return base.Channel.HistoricosTCGrafica(Mes, Year, Opciones, IdCliente);
        }
        
        public string HistoricoTCGrid(string Del, string Al, string posicion, string numRegistros, string IdCliente) {
            return base.Channel.HistoricoTCGrid(Del, Al, posicion, numRegistros, IdCliente);
        }
        
        public string HistoricosTranferGrafica(string Mes, string Year, PS_PACIFIC.Consumos.Opcion Opciones, string IdCliente) {
            return base.Channel.HistoricosTranferGrafica(Mes, Year, Opciones, IdCliente);
        }
        
        public string HistoricoTranferGrid(string Del, string Al, string posicion, string numRegistros, string IdCliente) {
            return base.Channel.HistoricoTranferGrid(Del, Al, posicion, numRegistros, IdCliente);
        }
        
        public string HistoricoSFEGrafica(string Mes, string Year, PS_PACIFIC.Consumos.Opcion Opciones, string idUsuario) {
            return base.Channel.HistoricoSFEGrafica(Mes, Year, Opciones, idUsuario);
        }
        
        public string HistoricoSFEGrid(string idUsuario, string del, string al, string posicion, string numRegistros) {
            return base.Channel.HistoricoSFEGrid(idUsuario, del, al, posicion, numRegistros);
        }
        
        public byte[] ObtenerPDF(string idUsuario, string UUID) {
            return base.Channel.ObtenerPDF(idUsuario, UUID);
        }
        
        public string ObtenerCFDi(string idUsuario, string UUID) {
            return base.Channel.ObtenerCFDi(idUsuario, UUID);
        }
        
        public string ActualizarEstatusCFDi(string idUsuario, string UUID, bool Estatus) {
            return base.Channel.ActualizarEstatusCFDi(idUsuario, UUID, Estatus);
        }
        
        public string DespliegaClientesFE(string idUsuario) {
            return base.Channel.DespliegaClientesFE(idUsuario);
        }
        
        public string CargarFolios(string idUsuario, string idDestinoUsuario, int Cantidad) {
            return base.Channel.CargarFolios(idUsuario, idDestinoUsuario, Cantidad);
        }
        
        public string FoliosRestantes(string idusuario) {
            return base.Channel.FoliosRestantes(idusuario);
        }
        
        public string TranferirFolios(string idUsuario, string idOrigenUsuario, string rfcDestino, int Cantidad) {
            return base.Channel.TranferirFolios(idUsuario, idOrigenUsuario, rfcDestino, Cantidad);
        }
        
        public string RazonSocial(string rfc) {
            return base.Channel.RazonSocial(rfc);
        }
        
        public string ConsultarComprasEmisores(string idusuario) {
            return base.Channel.ConsultarComprasEmisores(idusuario);
        }
        
        public bool ValidacionPassword(string Password) {
            return base.Channel.ValidacionPassword(Password);
        }
        
        public string DespliegaFormatos() {
            return base.Channel.DespliegaFormatos();
        }
        
        public string DespliegaEstatus() {
            return base.Channel.DespliegaEstatus();
        }
        
        public string DespliegaLista(PS_PACIFIC.Consumos.listas lista) {
            return base.Channel.DespliegaLista(lista);
        }
        
        public string DespliegaProveedor(PS_PACIFIC.Consumos.Servicios Servicio) {
            return base.Channel.DespliegaProveedor(Servicio);
        }
        
        public string BuscaTipoAsentamiento(string pais, string cp) {
            return base.Channel.BuscaTipoAsentamiento(pais, cp);
        }
        
        public string BuscaAsentamiento(string pais, string cp, string tipoAsentamiento) {
            return base.Channel.BuscaAsentamiento(pais, cp, tipoAsentamiento);
        }
        
        public string Paises() {
            return base.Channel.Paises();
        }
        
        public string BuscaEstados(string pais) {
            return base.Channel.BuscaEstados(pais);
        }
        
        public string BuscaMunicipio(string pais, string estado) {
            return base.Channel.BuscaMunicipio(pais, estado);
        }
        
        public string BuscaCiudad(string pais, string estado, string municipio) {
            return base.Channel.BuscaCiudad(pais, estado, municipio);
        }
        
        public string BuscaCP(string pais, string estado, string municipio, string ciudad) {
            return base.Channel.BuscaCP(pais, estado, municipio, ciudad);
        }
        
        public string finc() {
            return base.Channel.finc();
        }
    }
}
